spring:
  datasource:
    url: jdbc:mysql://192.168.88.130:3306/mybatis-plus?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    root: info
    cn.hmc.dao: debug